### PR TITLE
fix: change from harvest to beefy

### PR DESCRIPTION
**Pull request by RichJamo**
Hi all - here's my work for the beefy polygon adapter. I just wanted to check a couple of things before I submit:
I've run the test for **depositing** and **withdrawing** on 4 of the Beefy pools - DAI, USDC, WETH and WBTC - all single asset pools. They don't have a USDT pool or an sUSD pool. These are all working great. Let me know if I should test on any of the other pools (there are 168 in total!).
I have run a full test (deposit, stake, claim, unstake, withdraw) only on one pool as Beefy are only running one staking pool at the moment, and that's a BIFI staking pool with WATCH as a reward. Even on this one, I haven't been able to test the harvest function yet, as the WATCH token doesn't have enough liquidity on Quickswap yet and so any calls just revert.
I'm open to any other ideas on how we could test in different ways, so please let me know if I've missed something.
I've also deployed the contract to Polygon mainnet here (0x6E19677c79B09B7f0E357aBc8F673E3Ec41C2750), but I haven't really started experimenting with it yet - I suspect I need to deploy a bunch of other contracts on to polygon before that will be fully possible. Again, let me know if you think I could do some form of testing live on the polygon mainnet.
Thanks!

### CODE REVIEW

**Comment by uwe** [comment]
@RichJamo please don't delete/rename the harvest adapter (same goes for the `.env.example` file).

**Comment by RichJamo** [comment]
@uwe cool, please forgive some of my inexperience with github - happy to take any guidance!
Shall I re-add those two files and commit?
R

**Comment by uwe** [comment]
No problem. It's more than just two files. I would check out your forked repo in a different folder and then copy all files that are missing (harvest in the name) over. Then `git diff main...` (after commit) should show only your changes.

**Comment by RichJamo** [comment]
@uwe I've done as you suggested and put back all of the harvest files, as well as the env.example file. I've also gone through the code to put back some of the references to HarvestFinance files that I'd previously switched to Beefy Finance. 
However - note that the changes to hardhat.config.ts are still suited to running the Beefy tests on the polygon network, with the forking block set to quite a recent block. So both of these things have to be changed in order for the Harvest unit test to run again. I have made a note to try and find a way to set up the config file so that both can run consecutively, but am not sure I'll get to that in the next couple of days.
Also - note that I've still got three subsections of the Beefy unit test commented out (the three that make calls to a router), as there still isn't sufficient WATCH or BIFI liquidity on the two DEX's I've tried for the calls not to revert. I also intend to look at this in more detail when I have a moment.
Please shout if anything unclear or if any further questions.

**Comment by uwe** [comment]
Maybe someone from OptyFi can chime in. I had the impression that all adapters should be added to this repository (see also #1 which adds its own tests). But maybe that is not true, why would it be a template then?

**Comment by RichJamo** [comment]
@dhruvinparikh Hi Dhruvin - be great to get your feedback on my comment above - have submitted this for the Beefy Adapter - just want to make you aware of some of the details and ask for any feedback - thanks!

**Comment by dhruvinparikh** [comment]
> @dhruvinparikh Hi Dhruvin - be great to get your feedback on my comment above - have submitted this for the Beefy Adapter - just want to make you aware of some of the details and ask for any feedback - thanks!

Hi @RichJamo . Thank you for the contribution. Our core dev team always want to make sure that the adapter is able to interact with all the available pools of the protocol via test cases in order to detect edge cases if any.

**Comment by RichJamo** [comment]
@dhruvinparikh Cool, thanks for the heads up - am hard at work on it now - lots of pools to cover! Am going to borrow a little bit from what niklr did with the whale implementation to make it go a bit faster.

**Comment by dhruvinparikh** [comment]
> Maybe someone from OptyFi can chime in. I had the impression that all adapters should be added to this repository (see also #1 which adds its own tests). But maybe that is not true, why would it be a template then?

Hey @uwe ,

That is a good point. We will create a separate repository to keep adapters curated at one place. This is a template to provide reference to the builders. So builder should click on the green button that says "use this template" instead of forking.

**Comment by dhruvinparikh** [comment]
Closing this PR in favour of https://github.com/Opty-Fi/defi-adapters/pull/10

**Pull request closed without merging**
